name: zeus
description: A new Flutter application.
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  google_sign_in: ^4.5.1
  flutter_signin_button: ^1.0.0
  modal_progress_hud: ^0.1.3
  android_intent: ^0.3.7+2
  geolocator: ^5.3.1
  geocoder: ^0.2.1
  carousel_pro: ^1.0.0
  location_permissions: ^2.0.5
  image_picker: ^0.6.7+3
  firebase_storage: ^3.1.6
  google_nav_bar: ^3.1.0
  line_icons: ^0.2.0
  simple_url_preview: ^1.1.0
  workmanager: ^0.2.3
  flutter_local_notifications: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

  assets:
    - assets/